"""
TestRail publisher — wraps the existing TestRailService to create suites,
sections, cases, and optionally a test run from crawled test cases.

Hierarchy created:
  Project (existing)
    └── Suite  (new or reuse by name)
          └── Section (new or reuse by name — one per crawled page)
                └── Case (one per GeneratedTestCase)
  Run (optional, references all created cases)
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from ..services.testrail_service import TestRailService, TestRailError
from .models import GeneratedTestCase, GeneratedStep


# ── Formatter helpers ─────────────────────────────────────────────────────────


def _steps_to_testrail(steps: List[GeneratedStep]) -> str:
    """
    Serialise test steps into the TestRail "Preconditions" body format used
    by the Easy BDD testrail_runner (Feature: case style, YAML steps block).

    Output example:
        steps:
          - browser.open:
              url: ${base_url}
          - browser.fill:
              selector: "#email"
              value: ${username}
    """
    import yaml

    step_list = []
    for step in steps:
        params = {k: v for k, v in step.params.items() if v not in (None, "")}
        step_list.append({step.action: params or None})

    doc = {"steps": step_list}
    return yaml.dump(doc, default_flow_style=False, allow_unicode=True, sort_keys=False)


def _selector_fallbacks_comment(case: GeneratedTestCase) -> str:
    """Build a human-readable fallback comment to put in TestRail 'References'."""
    lines = []
    for step in case.steps:
        if step.selectors and len(step.selectors) > 1:
            primary = step.selectors[0].selector
            fallbacks = ", ".join(
                f"{r.selector} ({r.strategy})" for r in step.selectors[1:3]
            )
            lines.append(f"• {step.action}: primary={primary!r} | fallbacks: {fallbacks}")
    return "\n".join(lines) if lines else ""


# ── Main publisher ─────────────────────────────────────────────────────────────


class TestRailPublisher:
    """
    Publishes generated test cases to TestRail.

    Args:
        testrail: An authenticated TestRailService instance
        project_id: Target TestRail project ID
        suite_id: Existing suite ID, or None to create/find by name
        suite_name: Suite name to create or find (used when suite_id is None)
        section_name: Section name prefix (one section per crawled URL path)
    """

    def __init__(
        self,
        testrail: TestRailService,
        project_id: int,
        suite_id: Optional[int] = None,
        suite_name: str = "Auto-generated (Easy BDD Crawler)",
        section_name: str = "Crawled",
    ):
        self.tr = testrail
        self.project_id = project_id
        self._suite_id = suite_id
        self.suite_name = suite_name
        self.section_name = section_name

        # Cache
        self._section_cache: Dict[str, int] = {}  # section_name → section_id

    # ── Suite ─────────────────────────────────────────────────────────────────

    @property
    def suite_id(self) -> int:
        if self._suite_id:
            return self._suite_id
        self._suite_id = self._find_or_create_suite()
        return self._suite_id

    def _find_or_create_suite(self) -> int:
        try:
            suites = self.tr.get_suites(self.project_id)
            for s in suites:
                if s.get("name") == self.suite_name:
                    return s["id"]
            new_suite = self.tr.add_suite(
                self.project_id,
                name=self.suite_name,
                description="Test suite auto-generated by the Easy BDD Crawler browser extension.",
            )
            return new_suite["id"]
        except TestRailError as e:
            raise TestRailError(f"Could not find/create suite '{self.suite_name}': {e}") from e

    # ── Section ───────────────────────────────────────────────────────────────

    def _get_or_create_section(self, name: str) -> int:
        if name in self._section_cache:
            return self._section_cache[name]

        try:
            sections = self.tr.get_sections(self.project_id, suite_id=self.suite_id)
            for sec in sections:
                if sec.get("name") == name:
                    self._section_cache[name] = sec["id"]
                    return sec["id"]
            new_sec = self.tr.add_section(
                self.project_id,
                suite_id=self.suite_id,
                name=name,
                description=f"Auto-generated section for: {name}",
            )
            section_id = new_sec["id"]
            self._section_cache[name] = section_id
            return section_id
        except TestRailError as e:
            raise TestRailError(f"Could not find/create section '{name}': {e}") from e

    # ── Case ──────────────────────────────────────────────────────────────────

    def publish_case(
        self,
        case: GeneratedTestCase,
        section_name: Optional[str] = None,
    ) -> int:
        """
        Push a single GeneratedTestCase to TestRail as a Feature: case.

        Returns the TestRail case ID.
        """
        sec_name = section_name or self.section_name
        section_id = self._get_or_create_section(sec_name)

        body = _steps_to_testrail(case.steps)
        refs = _selector_fallbacks_comment(case)

        full_title = f"Feature: {case.name}"

        # Build payload with only safe standard fields.
        # custom_automation_status is a required field in some TestRail projects
        # (e.g. project 59). Default to 5 ("Completed" / automated).
        payload: Dict[str, Any] = {
            "title": full_title,
            "custom_preconds": body,
            "custom_automation_status": 5,
        }
        if refs:
            payload["refs"] = refs[:250]

        new_case = self.tr.add_case(section_id, **payload)

        # add_case may return {} on some API versions — guard defensively
        if not isinstance(new_case, dict) or "id" not in new_case:
            raise TestRailError(
                f"add_case returned unexpected response: {new_case!r}"
            )

        case_id: int = new_case["id"]
        case.testrail_case_id = case_id
        return case_id

    def publish_all(
        self,
        cases: List[GeneratedTestCase],
        group_by_url: bool = True,
    ) -> List[int]:
        """
        Publish a list of test cases; return list of TestRail case IDs.

        When group_by_url=True, cases from different URLs go into separate
        sections named after the URL path.
        """
        ids: List[int] = []
        push_errors: List[str] = []
        for case in cases:
            if group_by_url and case.url:
                from urllib.parse import urlparse
                path = urlparse(case.url).path.strip("/").replace("/", " > ") or "root"
                section_name = f"{self.section_name} / {path}"
            else:
                section_name = self.section_name

            try:
                cid = self.publish_case(case, section_name=section_name)
                ids.append(cid)
            except Exception as e:
                msg = f"[TestRail] Failed to push '{case.name}': {e}"
                print(msg)
                push_errors.append(msg)
                # If first case fails, surface the error immediately so the
                # caller can diagnose rather than silently skipping all cases.
                if not ids and len(push_errors) == 1:
                    raise TestRailError(msg) from e

        if push_errors:
            print(f"[TestRail] {len(push_errors)} case(s) failed, {len(ids)} succeeded.")
        return ids

    # ── Test Run ──────────────────────────────────────────────────────────────

    def create_run(
        self,
        case_ids: List[int],
        run_name: str = "Easy BDD Crawler Run",
        description: str = "",
    ) -> Tuple[int, str]:
        """
        Create a TestRail test run for the published cases.

        Returns (run_id, run_url).
        """
        run = self.tr.add_run(
            self.project_id,
            suite_id=self.suite_id,
            name=run_name,
            description=description or "Auto-generated run from Easy BDD Crawler.",
            case_ids=case_ids,
            include_all=False,
        )
        run_id: int = run["id"]
        run_url: str = f"{os.getenv('TESTRAIL_URL', '').rstrip('/')}/index.php?/runs/view/{run_id}"
        return run_id, run_url
